### ISSUE TITLE
Alternative fonts without a license requrements

### ISSUE THREAD

**Issue by ghost** [xivapi/vue-xivtooltips#24]
Per our [demo.html](https://github.com/nonowazu/vue-xivtooltips/blob/master/example/demo.html#L8), we use fonts from typekit.net, which (to my understanding) are licensed fonts. Given that we're now deploying these font-family suggestions in the css up to npm, we may want to provide some alternative fonts that don't require a license to use.

A loose set of TODO items:

- [x] Find alternative fonts that match
- [x] Add them as acceptable entries under the appropriate css `font-family` properties
- [x] Update `examples/demo.html` to use these acceptable alternative fonts
- [x] Update `README.md` to include free font(s) if required

For what it's worth, here's what it looks like without the licensed fonts:
![image](https://user-images.githubusercontent.com/53187143/99151644-43bc5a80-2662-11eb-8df7-7c8dd960f651.png)

**Comment by SaltedLevity** [comment]
I thought I had google font fallbacks set for these already, I'll take a look. I was under the impression you were okay with google fonts because they're all under an open font license/free to use even in commercial products? That still the case? Or do you want me to set default system fonts? Reason I'm asking is that the main font on these should be set to [Mada](https://fonts.google.com/specimen/Mada) so I'm concerned why it's not showing in your screenshot (should be almost everywhere).

Looks like I haven't updated the Benton Sans usage (that's from typekit), that's only used in the value line of the cast/recast/mp -- so shouldn't be too hard to swap. I think I have a google one written in my notes somewhere and just never implemented. Have to dig.

Users should also be free to continue using the Typekit fonts under that license as long as my adobe subscription stays current. I would like to continue offering this option to users (because I think the value line is a better match) with some way for them to opt-out if they so choose? Here's the overview from Adobe on font licensing: https://helpx.adobe.com/fonts/user-guide.html/fonts/using/font-licensing.ug.html that we can put with the font information.

**Comment by ArcaneDisgea** [comment]
solved by #26
